name: "Build Debezium Quarkus Extension Core"
description: "Builds the Debezium Extension core"

inputs:
  maven-cache-key:
    description: "The maven build cache key"
    required: true
  shell:
    description: "The shell to use"
    required: false
    default: bash
  distribution:
    description: "The Java distribution to use"
    required: false
    default: "graalvm"

runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java
      with:
        distribution: ${{ inputs.distribution }}
    - uses: ./.github/actions/maven-cache
      with:
        key: ${{ inputs.maven-cache-key }}
    - name: Build Parent
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw clean install -DskipITs -DskipTests -B
    - name: Build Debezium Quarkus Extension SPI
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw install -B -pl :debezium-quarkus-engine-spi-parent
    - name: Build Debezium Quarkus Extension Engine
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw install -B -pl :debezium-quarkus-engine-parent
    - name: Build Debezium Quarkus Extension Agroal
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw install -B -pl :debezium-quarkus-agroal-parent