name: "Build Debezium Quarkus Extension for mongodb"
description: "Builds the Debezium mongodb Extension"

inputs:
  maven-cache-key:
    description: "The maven build cache key"
    required: true
  shell:
    description: "The shell to use"
    required: false
    default: bash
  distribution:
    description: "The Java distribution to use"
    required: false
    default: "graalvm"
  maven-props:
    description: "Maven properties"
    required: true


runs:
  using: "composite"
  steps:
    - uses: ./.github/actions/setup-java
      with:
        distribution: ${{ inputs.distribution }}

    - uses: ./.github/actions/maven-cache
      with:
        key: ${{ inputs.maven-cache-key }}
    - name: Build Parent
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw clean install -DskipITs -DskipTests -B
    - name: Build Debezium Quarkus Extensions
      shell: ${{ inputs.shell }}
      run: >
        ./mvnw install -B -pl :debezium-quarkus-mongodb-parent  -am -amd -D${{maven-props}}
